// API Documentation Generator — Code Review Agent Phase 2.
//
// Parsит server/routes/*.js для построения docs/api-reference.md.
// Regex-based (Phase 1), достаточно для Express router-definitions.
//
// Extracts:
//   - router.METHOD('/path', handler)           — endpoint
//   - предшествующий JSDoc block                 — description + @query + @body + @response
//   - inline // comments                        — fallback description

import fs from 'node:fs';
import path from 'node:path';

const ROUTER_METHODS = ['get', 'post', 'put', 'patch', 'delete', 'all'];

function parseRouteFile(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  const lines = content.split('\n');
  const endpoints = [];

  // Найти default Router import и узнать name переменной (обычно "router")
  let routerVar = 'router';
  const rvMatch = content.match(/const\s+(\w+)\s*=\s*Router\s*\(/);
  if (rvMatch) routerVar = rvMatch[1];

  // Для каждой строки найти router.METHOD('path'
  const endpointRegex = new RegExp(`${routerVar}\\.(${ROUTER_METHODS.join('|')})\\s*\\(\\s*['\`"]([^'\`"]+)['\`"]`, 'g');

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const m = endpointRegex.exec(line);
    if (!m) { endpointRegex.lastIndex = 0; continue; }
    endpointRegex.lastIndex = 0; // reset per-line

    const method = m[1].toUpperCase();
    const routePath = m[2];

    // Собираем preceding comment block (last N lines before endpoint)
    const comments = [];
    for (let j = i - 1; j >= Math.max(0, i - 30); j--) {
      const prev = lines[j].trim();
      if (prev === '') { if (comments.length) break; else continue; }
      if (prev.startsWith('//')) {
        comments.unshift(prev.replace(/^\/\/+\s*/, ''));
      } else if (prev.startsWith('*') || prev.startsWith('/**') || prev.startsWith('*/')) {
        comments.unshift(prev.replace(/^\/?\*+\/?\s*/, ''));
      } else {
        break;
      }
    }

    endpoints.push({
      method,
      path: routePath,
      description: comments.join(' ').trim(),
      line: i + 1,
    });
  }

  return { endpoints };
}

// Мэппинг mount-points из server/index.js: app.use('/api/xyz', xyzRouter)
// → мы должны знать какой prefix добавить к endpoint path.
function parseMounts(indexJsPath) {
  const content = fs.readFileSync(indexJsPath, 'utf8');
  const mounts = new Map(); // routerName → prefix

  // import xyzRouter from './routes/xyz.js';
  const imports = [...content.matchAll(/import\s+(\w+)\s+from\s+['"]\.\/routes\/(\w+)\.js['"]/g)];
  const importedToFile = new Map();
  for (const m of imports) importedToFile.set(m[1], m[2]);

  // app.use('/api/xyz', xyzRouter)   ИЛИ   app.use('/api', xyzRouter)
  const mountRegex = /app\.use\(\s*['"]([^'"]+)['"]\s*,\s*(\w+)\s*\)/g;
  let m;
  while ((m = mountRegex.exec(content)) !== null) {
    const prefix = m[1];
    const routerVar = m[2];
    const file = importedToFile.get(routerVar);
    if (file) mounts.set(file, prefix);
  }

  return mounts;
}

// Генерация markdown. Группируем по файлу (= логическая группа).
export function generateApiReference({ repoRoot }) {
  const routesDir = path.join(repoRoot, 'server', 'routes');
  const indexJs = path.join(repoRoot, 'server', 'index.js');

  const mounts = parseMounts(indexJs);
  const files = fs.readdirSync(routesDir).filter(f => f.endsWith('.js'));

  const sections = [];
  let totalEndpoints = 0;

  for (const file of files.sort()) {
    const base = file.replace('.js', '');
    const filePath = path.join(routesDir, file);
    const prefix = mounts.get(base) || '/api';
    const { endpoints } = parseRouteFile(filePath);
    if (!endpoints.length) continue;
    totalEndpoints += endpoints.length;

    // De-duplicate paths (same method+path might appear for multi-line matches)
    const seen = new Set();
    const unique = endpoints.filter(e => {
      const k = `${e.method} ${e.path}`;
      if (seen.has(k)) return false;
      seen.add(k);
      return true;
    });

    sections.push({ file, base, prefix, endpoints: unique });
  }

  const now = new Date().toISOString().slice(0, 16).replace('T', ' ') + ' UTC';
  const lines = [
    '# SCC API Reference',
    '',
    `> Auto-generated by code-review-agent. Last updated: ${now}.`,
    `> Source: \`server/routes/*.js\`. Mount points: \`server/index.js\`.`,
    `> Всего endpoints: **${totalEndpoints}** в ${sections.length} группах.`,
    '',
    '## Index',
    '',
  ];

  // ToC
  for (const s of sections) {
    lines.push(`- [${capitalize(s.base)}](#${s.base}) — ${s.endpoints.length} endpoint${s.endpoints.length === 1 ? '' : 's'}`);
  }
  lines.push('');

  // Sections
  for (const s of sections) {
    lines.push(`## ${capitalize(s.base)}`);
    lines.push('');
    lines.push(`Mount: \`${s.prefix}\` (from \`server/routes/${s.file}\`)`);
    lines.push('');
    lines.push('| Method | Path | Description |');
    lines.push('|---|---|---|');
    for (const e of s.endpoints) {
      const fullPath = joinPaths(s.prefix, e.path);
      const desc = (e.description || '—').replace(/\|/g, '\\|').slice(0, 200);
      lines.push(`| \`${e.method}\` | \`${fullPath}\` | ${desc} |`);
    }
    lines.push('');
  }

  return { markdown: lines.join('\n'), stats: { totalEndpoints, files: sections.length } };
}

function joinPaths(prefix, routePath) {
  // routes внутри часто начинаются с абсолютного пути типа /sites/:id/articles
  // а prefix может быть /api или /api/sites — надо избежать дубля.
  if (routePath.startsWith(prefix)) return routePath;
  if (prefix === '/api' || prefix.endsWith('/')) {
    return (prefix.replace(/\/$/, '') + (routePath.startsWith('/') ? '' : '/') + routePath).replace(/\/+/g, '/');
  }
  // Prefix типа /api/agents + path /:id → /api/agents/:id
  if (routePath.startsWith('/')) return prefix + routePath;
  return prefix + '/' + routePath;
}

function capitalize(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// Public entry
export function writeApiReference(repoRoot) {
  const { markdown, stats } = generateApiReference({ repoRoot });
  const outPath = path.join(repoRoot, 'docs', 'api-reference.md');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, markdown);
  return { path: outPath, ...stats };
}
